### PR TITLE
WMP update: added filetype attribute and included nuclide name

### PR DESCRIPTION
**Pull request by liangjg**
This tries to address issue #2 suggested by @paulromano :

- added an attribute to the library `filetype` as `data_wmp`
- changed the group name from `nuclide` to GND nuclide name

like:

image

### CODE REVIEW

**Comment by liangjg** [comment]
@paulromano You may check an example library: https://github.com/liangjg/WMP_Library/releases/download/v1.0.1-alpha/027058m1.h5

**Comment by paulromano** [comment]
@liangjg The example file looks good. Thanks for taking the time to do this!

**Comment by paulromano** [comment]
Actually one more thing you may want to consider is making `/version` an attribute rather than a dataset to match the other formats for OpenMC.

**Comment by liangjg** [comment]
@paulromano `version` is now an attribute, similar as other formats.

**Pull request merged**
